FROM node:18.19-buster

# Alpine Linux CMD group
# RUN addgroup dev && addouser -S -G dev dev && apk add --no-cache make gcc g++ python3

# Debian CMD group
RUN addgroup dev && adduser --uid 1001 --ingroup dev --shell /bin/bash --disabled-password --gecos "" dev

RUN apt-get update && apt-get install -y build-essential python3-distutils git apt-utils sudo

WORKDIR /app

RUN sudo chown dev:dev /app

COPY package*.json ./

RUN npm i --build-from-source && npm ci

COPY . .

USER dev

ENV PORT=8080

EXPOSE 8080

#CMD ["sh", "-c", "until nc -z postgres 5432", "do sleep 1", "done", "npm run prisma generate", "npm run prisma migrate", "npm run start:dev" ]

#CMD ["sh", "-c", "npm run prisma generate", "npm run prisma migrate", "npm run start:dev" ]

