version: '3.9'

services:
  server:
    build:
      context:
        dockerfile: Dockerfile.test
        command: npm test
        container_name: homegrown-test-server
        ports:
          -'1234:1234'
        volumes:
          -./:/
  db:
    image: postgres:14
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121314
      POSTGRES_DB: homegrownprismadb