version: "3.8"
services: 
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121314
      POSTGRES_DB: homegrownprismadb

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5845:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "devin.phat97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD : 121314