version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121314
      POSTGRES_DB: homegrownprismadb