version: "3.8"
services: 
  server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    evnironment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homegrownprismadb