FROM node:20-alpine3.18

RUN addgroup dev && adduser -S -G dev dev


WORKDIR /app

RUN chown -R dev:dev /app

USER dev

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=8080

EXPOSE 8080

CMD [ "prisma", "generate", && "npm","run", "start:dev" ]