FROM node:20.11-alpine3.18

RUN addgroup dev && adduser -S -G dev dev && apk add --no-cache make gcc g++ python3

WORKDIR /app

RUN chown dev:dev /app

USER dev

COPY package*.json ./

COPY . .

ENV PORT=8080

EXPOSE 8080

CMD ["sh", "-c", "npm run prisma generate && npm run prisma migrate && npm run start:dev" ]
